The ``7-base_geometry`` module
======================

Using ``BaseGeometry``
-------------------

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
	>>> bg = BaseGeometry(None)
	Traceback (most recent call last):
	...
	TypeError: BaseGeometry() takes no arguments

	>>> bg = BaseGeometry()

	>>> bg.integer_validator("my_int", 12)

	>>> bg.integer_validator("width", 89)

	>>> bg.integer_validator("name", "John")
	Traceback (most recent call last):
	...
	TypeError: name must be an integer

	>>> bg.integer_validator("age", 0)
	Traceback (most recent call last):
	...
	ValueError: age must be greater than 0

	>>> bg.integer_validator("distance", -4)
	Traceback (most recent call last):
	...
	ValueError: distance must be greater than 0

	>>> bg.integer_validator(3, 500)

	>>> bg.integer_validator(-5, 9)

	>>> bg.area()
	Traceback (most recent call last):
	...
	Exception: area() is not implemented

	>>> bg.area(550)
	Traceback (most recent call last):
	...
	TypeError: area() takes 1 positional argument but 2 were given

	>>> bg.integer_validator("distance", None)
	Traceback (most recent call last):
	...
	TypeError: distance must be an integer

	>>> bg.integer_validator("distance", 10.5)
	Traceback (most recent call last):
	...
	TypeError: distance must be an integer

	>>> bg.integer_validator("distance", (1,2,3))
	Traceback (most recent call last):
	...
	TypeError: distance must be an integer

	>>> bg.integer_validator("distance", [1,2,3])
	Traceback (most recent call last):
	...
	TypeError: distance must be an integer

	>>> bg.integer_validator("distance", {'id': 8})
	Traceback (most recent call last):
	...
	TypeError: distance must be an integer

	>>> bg.integer_validator("distance", False)
	Traceback (most recent call last):
	...
	ValueError: distance must be greater than 0

	>>> bg.integer_validator("distance", True)

	>>> bg.integer_validator("distance")
	Traceback (most recent call last):
	...
	TypeError: integer_validator() missing 1 required positional argument: 'value'

	>>> bg.integer_validator()
	Traceback (most recent call last):
	...
	TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

	>>> bg.integer_validator(None)
	Traceback (most recent call last):
	...
	TypeError: integer_validator() missing 1 required positional argument: 'value'

	>>> bg.integer_validator(None, None)
	Traceback (most recent call last):
	...
	TypeError: None must be an integer
